version: '2'

services:
  gstreamer:
    image: gstreamer
    container_name: gstreamer
    restart: unless-stopped
    command: gst-launch-1.0 -v v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! application/x-rtp, media=video, encoding-name="H264", payload=96 ! udpsink port=5002 host=localhost
    network_mode: host

  janus-gateway:
    image: janus-gateway
    container_name: janus-gateway
    restart: unless-stopped
    volumes:
      - ./../../etc/janus/:/opt/janus/etc/janus/
    expose:
      - 8088
      - 5002
    network_mode: host

    babycam:
      image: babycam
      container_name: babycam
      restart: unless-stopped
      expose:
      - 80
